### ISSUE TITLE
Remove log4j dependency from compile scope

### ISSUE THREAD

**Issue by jochenchrist** [ManfredTremmel/mt-bean-validators#9]
The library has the log4j dependency in compile scope.
This imposes a particular logging implementation on downstream projects.

Please remove any specific implementations or SLF4J bindings from compile or runtime scope, so that downstream projects have free choice for a binding (such as logback-classic).

It is totally OK to have logging dependencies in test scope.

**Comment by ManfredTremmel** [comment]
Hi @jochenchrist ,
you are totaly right, I only used the loger in the test. I'll move it to the test scope

**Comment by ManfredTremmel** [comment]
Depandency changes is now released with 0.54.0.
I also reworked all the dependencies of the coresponding projects and splitted gwtp spring integration stuff in a separate package. Should be much clearer to separate frontend and backend stuff now in GWT projects.
